version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"  # S'il y a un Dockerfile à la racine du repo
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/janus-infra"  # Pour le Dockerfile de ton infra
    schedule:
      interval: "daily"
