---
# version: '3.8'

services:
  janus-nginx1:
    image: nginx:alpine
    container_name: janus-nginx1
    restart: always
    depends_on:
      - janus-core1
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - '8081:80'
    security_opt:
      - 'no-new-privileges=true'
    networks:
      janus-prod-net:
        ipv4_address: 172.16.238.10

  janus-core1:
    image: php:fpm
    container_name: janus-core1
    restart: always
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    security_opt:
      - 'no-new-privileges=true'
    ports:
      - '9000:9000'
    networks:
      janus-prod-net:
        ipv4_address: 172.16.238.11

  janus-backend1:
    image: mysql:latest
    container_name: janus-backend1
    restart: always
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: repl_password
      # command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=mydatabase
    volumes:
      - mysql_data:/var/lib/mysql
    security_opt:
      - 'no-new-privileges=true'
    networks:
      janus-prod-net:
        ipv4_address: 172.16.238.12

networks:
  janus-prod-net:
    ipam:
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

volumes:
  mysql_data:
