
# version: '3.8'

services:
  janus-nginx1:
    image: nginx:alpine
    container_name: janus-nginx1
    volumes:
      - ../janus-frontend/janus-website:/usr/share/nginx/html:z
      - ../janus-frontend/janus-conf-nginx:/etc/nginx/conf.d:z
      - ../janus-frontend/janus-db-connect:/home/janus-storage/janus-db-connect:z
      - ../janus-infra/janus-certs:/etc/nginx/certs:z
    ports:
   #  - "8081:80"
      - "8443:443"
    depends_on:
      - janus-php
    restart: always
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    security_opt:
      - "no-new-privileges=true"
    networks:
      - janus-prod-net

  janus-php:
    image: imtjanus/janus-php:8.2-fpm
    container_name: janus-php
    restart: always
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ../janus-frontend/janus-website:/usr/share/nginx/html:z
      - ../janus-frontend/janus-db-connect:/home/janus-storage/janus-db-connect:z
    ports:
      - "9000:9000"
    security_opt:
      - "no-new-privileges=true"
    networks:
      - janus-prod-net

  janus-mysql:
    image: mysql:latest
    container_name: janus-mysql
    restart: always
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: janus_db
      MYSQL_USER: janus
      MYSQL_PASSWORD: janus
      # command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=mydatabase
    #security_opt:
    #- "no-new-privileges=true"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - janus-prod-net

networks:
  janus-prod-net:

volumes:
  mysql_data:
