# version: '3.8'

services:
  janus-haproxy:
    image: haproxy:latest
    volumes:
      - ../janus-infra/janus-haproxy:/usr/local/etc/haproxy:z
      - ../janus-infra/janus-certs:/usr/local/certs:z
    ports:
      - "8445:8445"
    container_name: janus-haproxy
    depends_on:
      - janus-nginx1
      - janus-nginx2
    networks:
      - janus-prod-net

  janus-nginx1:
    image: nginx:alpine
    container_name: janus-nginx1
    volumes:
      - ../janus-frontend/janus-website:/usr/share/nginx/html:z
      - ../janus-frontend/janus-conf-nginx:/etc/nginx/conf.d:z
      - ../janus-frontend/janus-db-connect:/home/janus-storage/janus-db-connect:z
      - ../janus-infra/janus-certs:/etc/nginx/certs:z
      - ../janus-frontend/public:/usr/share/nginx/html/slim:z
    ports:
   #  - "8081:80"
      - "8443:443"
    depends_on:
      - janus-php
    restart: always
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    security_opt:
      - "no-new-privileges=true"
    networks:
      - janus-prod-net 

  janus-nginx2:
      image: nginx:alpine
      container_name: janus-nginx2
      volumes:
        - ../janus-frontend/janus-website:/usr/share/nginx/html:z
        - ../janus-frontend/janus-conf-nginx:/etc/nginx/conf.d:z
        - ../janus-frontend/janus-db-connect:/home/janus-storage/janus-db-connect:z
        - ../janus-infra/janus-certs:/etc/nginx/certs:z
        - ../janus-frontend/public:/usr/share/nginx/html/slim:z
      ports:
     #  - "8081:80"
        - "8444:443"
      depends_on:
        - janus-php
      restart: always
      healthcheck:
        test: ["CMD", "ping", "-c", "1", "127.0.0.1"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 5s
      security_opt:
        - "no-new-privileges=true"
      networks:
        - janus-prod-net

  janus-php:
    image: imtjanus/janus-php:8.2-fpm
    container_name: janus-php
    restart: always
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ../janus-frontend/janus-website:/usr/share/nginx/html:z
      - ../janus-frontend/janus-db-connect:/home/janus-storage/janus-db-connect:z
      - ../janus-frontend/public:/usr/share/nginx/html/slim:z
      - ../janus-frontend/composer:/usr/share/nginx/composer:z
    ports:
      - "9000:9000"
    security_opt:
      - "no-new-privileges=true"
    networks:
      - janus-prod-net

  janus-mysql:
    image: mysql:latest
    container_name: janus-mysql
    restart: always
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: janus_db
      MYSQL_USER: janus
      MYSQL_PASSWORD: janus
    volumes:
      - mysql_data:/var/lib/mysql
      - ./janus-db:/docker-entrypoint-initdb.d/:z
    ports:
      - "3306:3306"
    networks:
      - janus-prod-net

  janus-core:
    image: imtjanus/janus-core:latest
    container_name: janus-core
    restart: always
    network_mode: host
    depends_on:
      - janus-mysql

networks:
  janus-prod-net:

volumes:
  mysql_data:
